---
Name: deploynautroutes
After:
  - '#rootroutes'
---
Director:
  rules:
    '': '->naut'
    'naut/api//$Project/$Environment/$OtherID': 'DeploynautAPI'
    'naut/project/$Project/snapshots': 'Snapshots'
    'naut/project/$Project/environment/$Environment/overview': 'EnvironmentOverview'
    'naut/project/$Project/git': 'GitDispatcher'
    'naut/project/$Project/environment/$Environment/deploys': 'DeployDispatcher'
    'naut/project/$Project/environment/$Environment/approvals': 'ApprovalsDispatcher'
    'naut/project/$Project/environment/$Environment/letmein': 'LetmeinDispatcher'
    'naut': 'DNRoot'
