---
Name: deploynautroutes
After:
  - '#rootroutes'
---
Director:
  rules:
    '': '->naut'
    'naut/api//$Project/$Environment/$OtherID': 'DeploynautAPI'
    'naut': 'DNRoot'
    'v1/project/$Project/environment/$Environment/deployment': 'DNDeploymentDispatcher'
